import type { ZonaData } from '../types/avaluo.types';

const obs = (nombre: string, entorno: string) => `Zona ${nombre} en Estelí con entorno ${entorno}; valores base iniciales centralizados para ajustes técnicos futuros.`;

export const ESTELI_ZONES: ZonaData[] = [
  { id: 'esteli-centro', ciudad: 'Estelí', zona: 'Centro de Estelí', nombre: 'Centro de Estelí', clasificacion: 'A+', tipoEntorno: 'Comercial / urbano premium', factorPlusvalia: 1.28, valorTerrenoM2: 170, valorConstruccionM2: 620, observacionTecnica: obs('Centro de Estelí', 'Comercial / urbano premium') },
  { id: 'esteli-el-rosario', ciudad: 'Estelí', zona: 'El Rosario', nombre: 'El Rosario', clasificacion: 'A', tipoEntorno: 'Residencial alta', factorPlusvalia: 1.20, valorTerrenoM2: 150, valorConstruccionM2: 590, observacionTecnica: obs('El Rosario', 'Residencial alta') },
  { id: 'esteli-las-colinas', ciudad: 'Estelí', zona: 'Las Colinas', nombre: 'Las Colinas', clasificacion: 'A', tipoEntorno: 'Residencial alta', factorPlusvalia: 1.22, valorTerrenoM2: 155, valorConstruccionM2: 600, observacionTecnica: obs('Las Colinas', 'Residencial alta') },
  { id: 'esteli-villa-esperanza', ciudad: 'Estelí', zona: 'Villa Esperanza', nombre: 'Villa Esperanza', clasificacion: 'B+', tipoEntorno: 'Residencial media alta', factorPlusvalia: 1.12, valorTerrenoM2: 120, valorConstruccionM2: 530, observacionTecnica: obs('Villa Esperanza', 'Residencial media alta') },
  { id: 'esteli-norte', ciudad: 'Estelí', zona: 'Estelí Norte', nombre: 'Estelí Norte', clasificacion: 'B', tipoEntorno: 'Residencial medio', factorPlusvalia: 1.05, valorTerrenoM2: 105, valorConstruccionM2: 500, observacionTecnica: obs('Estelí Norte', 'Residencial medio') },
  { id: 'esteli-sur', ciudad: 'Estelí', zona: 'Estelí Sur', nombre: 'Estelí Sur', clasificacion: 'B', tipoEntorno: 'Residencial medio', factorPlusvalia: 1.04, valorTerrenoM2: 100, valorConstruccionM2: 490, observacionTecnica: obs('Estelí Sur', 'Residencial medio') },
  { id: 'esteli-bella-vista', ciudad: 'Estelí', zona: 'Bella Vista', nombre: 'Bella Vista', clasificacion: 'B', tipoEntorno: 'Residencial medio', factorPlusvalia: 1.02, valorTerrenoM2: 95, valorConstruccionM2: 475, observacionTecnica: obs('Bella Vista', 'Residencial medio') },
  { id: 'esteli-boris-vega', ciudad: 'Estelí', zona: 'Boris Vega', nombre: 'Boris Vega', clasificacion: 'C', tipoEntorno: 'Popular consolidado', factorPlusvalia: 0.92, valorTerrenoM2: 72, valorConstruccionM2: 430, observacionTecnica: obs('Boris Vega', 'Popular consolidado') },
  { id: 'esteli-oscar-gamez', ciudad: 'Estelí', zona: 'Oscar Gámez', nombre: 'Oscar Gámez', clasificacion: 'C', tipoEntorno: 'Popular', factorPlusvalia: 0.90, valorTerrenoM2: 68, valorConstruccionM2: 420, observacionTecnica: obs('Oscar Gámez', 'Popular') },
  { id: 'esteli-panama-soberana', ciudad: 'Estelí', zona: 'Panamá Soberana', nombre: 'Panamá Soberana', clasificacion: 'C', tipoEntorno: 'Popular', factorPlusvalia: 0.89, valorTerrenoM2: 65, valorConstruccionM2: 415, observacionTecnica: obs('Panamá Soberana', 'Popular') },
  { id: 'esteli-alfredo-lazo', ciudad: 'Estelí', zona: 'Alfredo Lazo', nombre: 'Alfredo Lazo', clasificacion: 'C', tipoEntorno: 'Popular', factorPlusvalia: 0.88, valorTerrenoM2: 62, valorConstruccionM2: 410, observacionTecnica: obs('Alfredo Lazo', 'Popular') },
  { id: 'esteli-la-thompson', ciudad: 'Estelí', zona: 'La Thompson', nombre: 'La Thompson', clasificacion: 'B', tipoEntorno: 'Residencial medio', factorPlusvalia: 1.00, valorTerrenoM2: 88, valorConstruccionM2: 460, observacionTecnica: obs('La Thompson', 'Residencial medio') },
  { id: 'esteli-la-sirena', ciudad: 'Estelí', zona: 'La Sirena', nombre: 'La Sirena', clasificacion: 'C', tipoEntorno: 'Residencial popular', factorPlusvalia: 0.86, valorTerrenoM2: 58, valorConstruccionM2: 400, observacionTecnica: obs('La Sirena', 'Residencial popular') },
  { id: 'esteli-miguel-alonso', ciudad: 'Estelí', zona: 'Miguel Alonso', nombre: 'Miguel Alonso', clasificacion: 'C', tipoEntorno: 'Popular', factorPlusvalia: 0.87, valorTerrenoM2: 60, valorConstruccionM2: 405, observacionTecnica: obs('Miguel Alonso', 'Popular') },
  { id: 'esteli-14-de-abril', ciudad: 'Estelí', zona: '14 de Abril', nombre: '14 de Abril', clasificacion: 'C', tipoEntorno: 'Popular', factorPlusvalia: 0.86, valorTerrenoM2: 58, valorConstruccionM2: 400, observacionTecnica: obs('14 de Abril', 'Popular') },
];
